"""empty message

Revision ID: e565041c5419
Revises: 
Create Date: 2021-05-29 20:35:30.712165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e565041c5419'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('championship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=False),
    sa.Column('has_ended', sa.Boolean(), nullable=True),
    sa.Column('players_amount', sa.Integer(), nullable=True),
    sa.Column('best_of_type', sa.Integer(), nullable=False),
    sa.Column('sets_final_score', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['championship_id'], ['championship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('club_role', sa.String(length=15), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('matches_won', sa.Integer(), nullable=True),
    sa.Column('matches_lost', sa.Integer(), nullable=True),
    sa.Column('sets_won', sa.Integer(), nullable=True),
    sa.Column('sets_lost', sa.Integer(), nullable=True),
    sa.Column('plays_won', sa.Integer(), nullable=True),
    sa.Column('plays_lost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lost_club_matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'club_id')
    )
    op.create_table('lost_player_matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('has_ended', sa.Boolean(), nullable=True),
    sa.Column('plays_final_loser_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('offense', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('shot', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('perception', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Integer(), nullable=False),
    sa.Column('mindset', sa.Integer(), nullable=False),
    sa.Column('technique', sa.Integer(), nullable=False),
    sa.Column('service', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('won_club_matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'club_id')
    )
    op.create_table('won_player_matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    op.create_table('lost_club_sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.PrimaryKeyConstraint('set_id', 'club_id')
    )
    op.create_table('lost_player_sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.PrimaryKeyConstraint('set_id', 'player_id')
    )
    op.create_table('won_club_sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.PrimaryKeyConstraint('set_id', 'club_id')
    )
    op.create_table('won_player_sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.PrimaryKeyConstraint('set_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('won_player_sets')
    op.drop_table('won_club_sets')
    op.drop_table('lost_player_sets')
    op.drop_table('lost_club_sets')
    op.drop_table('won_player_matches')
    op.drop_table('won_club_matches')
    op.drop_table('skill')
    op.drop_table('set')
    op.drop_table('lost_player_matches')
    op.drop_table('lost_club_matches')
    op.drop_table('player')
    op.drop_table('match')
    op.drop_table('season')
    op.drop_table('club')
    op.drop_table('championship')
    # ### end Alembic commands ###
